update=Tue 22 Jul 2014 22:30:11 NZST
last_client=eeschema
[general]
version=1
[eeschema]
version=1
PageLayoutDescrFile=
SubpartIdSeparator=0
SubpartFirstId=65
LibDir=/home/xav/kicad;/home/xav/kicad/Libs;/home/xav/kicad/common
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=PCM2707
LibName2=valves
LibName3=power
LibName4=device
LibName5=logo
LibName6=audio
LibName7=con-usb
LibName8=v-reg
LibName9=conn
